<?xml version="1.0" encoding="UTF-8"?>
<!-- 内部DTD 亦可通过外部DTD来实现-->
<!DOCTYPE generatorConfiguration

        [
                <!ELEMENT generatorConfiguration (properties?, classPathEntry*, context+)>

                <!ELEMENT properties EMPTY>
                <!ATTLIST properties
                        resource CDATA #IMPLIED
                        url CDATA #IMPLIED>
                <!--
                    括号里是声明出现的次序:
                    *: 出现任意次,包括0次
                    ?: 出现最多一次
                    |:选择之一
                    +: 出现最少1次
                    如果没有上述符号:必须且只能出现一次
                 -->
                <!ELEMENT context (property*, plugin*, commentGenerator?, (connectionFactory | jdbcConnection), javaTypeResolver?,
                        javaModelGenerator?, sqlMapGenerator?, javaClientGenerator?, javaServiceGenerator?,table+)>
                <!ATTLIST context id ID #REQUIRED
                        defaultModelType CDATA #IMPLIED
                        targetRuntime CDATA #IMPLIED
                        introspectedColumnImpl CDATA #IMPLIED>

                <!ELEMENT connectionFactory (property*)>
                <!ATTLIST connectionFactory
                        type CDATA #IMPLIED>

                <!ELEMENT jdbcConnection (property*)>
                <!ATTLIST jdbcConnection
                        driverClass CDATA #REQUIRED
                        connectionURL CDATA #REQUIRED
                        userId CDATA #IMPLIED
                        password CDATA #IMPLIED>

                <!ELEMENT classPathEntry EMPTY>
                <!ATTLIST classPathEntry
                        location CDATA #REQUIRED>

                <!ELEMENT property EMPTY>
                <!ATTLIST property
                        name CDATA #REQUIRED
                        value CDATA #REQUIRED>

                <!ELEMENT plugin (property*)>
                <!ATTLIST plugin
                        type CDATA #REQUIRED>

                <!ELEMENT javaModelGenerator (property*)>
                <!ATTLIST javaModelGenerator
                        targetPackage CDATA #REQUIRED
                        targetProject CDATA #REQUIRED>

                <!ELEMENT javaTypeResolver (property*)>
                <!ATTLIST javaTypeResolver
                        type CDATA #IMPLIED>

                <!ELEMENT sqlMapGenerator (property*)>
                <!ATTLIST sqlMapGenerator
                        targetPackage CDATA #REQUIRED
                        targetProject CDATA #REQUIRED>

                <!ELEMENT javaClientGenerator (property*)>
                <!ATTLIST javaClientGenerator
                        type CDATA #REQUIRED
                        targetPackage CDATA #REQUIRED
                        targetProject CDATA #REQUIRED
                        implementationPackage CDATA #IMPLIED>

                <!ELEMENT javaServiceGenerator (property*)>
                <!ATTLIST javaServiceGenerator
                        targetPackage CDATA #REQUIRED
                        implementationPackage CDATA #REQUIRED
                        targetProject CDATA #REQUIRED>

                <!ELEMENT table (property*, generatedKey?, domainObjectRenamingRule?, columnRenamingRule?, (columnOverride | ignoreColumn | ignoreColumnsByRegex)*) >
                <!ATTLIST table
                        catalog CDATA #IMPLIED
                        schema CDATA #IMPLIED
                        tableName CDATA #REQUIRED
                        alias CDATA #IMPLIED
                        domainObjectName CDATA #IMPLIED
                        mapperName CDATA #IMPLIED
                        sqlProviderName CDATA #IMPLIED
                        enableInsert CDATA #IMPLIED
                        enableSelectByPrimaryKey CDATA #IMPLIED
                        enableSelectByExample CDATA #IMPLIED
                        enableUpdateByPrimaryKey CDATA #IMPLIED
                        enableDeleteByPrimaryKey CDATA #IMPLIED
                        enableDeleteByExample CDATA #IMPLIED
                        enableCountByExample CDATA #IMPLIED
                        enableUpdateByExample CDATA #IMPLIED
                        selectByPrimaryKeyQueryId CDATA #IMPLIED
                        selectByExampleQueryId CDATA #IMPLIED
                        modelType CDATA #IMPLIED
                        escapeWildcards CDATA #IMPLIED
                        delimitIdentifiers CDATA #IMPLIED
                        delimitAllColumns CDATA #IMPLIED>

                <!ELEMENT columnOverride (property*)>
                <!ATTLIST columnOverride
                        column CDATA #REQUIRED
                        property CDATA #IMPLIED
                        javaType CDATA #IMPLIED
                        jdbcType CDATA #IMPLIED
                        typeHandler CDATA #IMPLIED
                        isGeneratedAlways CDATA #IMPLIED
                        delimitedColumnName CDATA #IMPLIED>

                <!ELEMENT ignoreColumn EMPTY>
                <!ATTLIST ignoreColumn
                        column CDATA #REQUIRED
                        delimitedColumnName CDATA #IMPLIED>


                <!ELEMENT ignoreColumnsByRegex (except*)>
                <!ATTLIST ignoreColumnsByRegex
                        pattern CDATA #REQUIRED>

                <!ELEMENT except EMPTY>
                <!ATTLIST except
                        column CDATA #REQUIRED
                        delimitedColumnName CDATA #IMPLIED>

                <!ELEMENT generatedKey EMPTY>
                <!ATTLIST generatedKey
                        column CDATA #REQUIRED
                        sqlStatement CDATA #REQUIRED
                        identity CDATA #IMPLIED
                        type CDATA #IMPLIED>

                <!ELEMENT domainObjectRenamingRule EMPTY>
                <!ATTLIST domainObjectRenamingRule
                        searchString CDATA #REQUIRED
                        replaceString CDATA #IMPLIED>

                <!ELEMENT columnRenamingRule EMPTY>
                <!ATTLIST columnRenamingRule
                        searchString CDATA #REQUIRED
                        replaceString CDATA #IMPLIED>

                <!ELEMENT commentGenerator (property*)>
                <!ATTLIST commentGenerator
                        type CDATA #IMPLIED>
                ]
        >
<generatorConfiguration>
    <!-- 数据库驱动:选择你的本地硬盘上面的数据库驱动包-->
    <!--<classPathEntry  location="/Users/Winterchen/Downloads/mysql-connector-java-5.1.25.jar"/>-->
    <context id="ables"  targetRuntime="MyBatis3">
        <!--<commentGenerator>
            <property name="suppressDate" value="true"/>
            &lt;!&ndash; 是否去除自动生成的注释 true：是 ： false:否 &ndash;&gt;
            <property name="suppressAllComments" value="true"/>
        </commentGenerator>-->
        <plugin type="me.jason.generator.PluginChain" />
        <plugin type="me.jason.generator.SerializablePlugin" />
        <plugin type="org.mybatis.generator.plugins.ToStringPlugin" />
        <commentGenerator type="me.jason.generator.CommentGenerator"/>
        <!--数据库链接URL，用户名、密码 -->
        <jdbcConnection driverClass="com.mysql.jdbc.Driver"
                        connectionURL="jdbc:mysql://localhost:3306/yyzx?characterEncoding=utf8&amp;useSSL=false"
                        userId="root" password="123456">
        </jdbcConnection>
        <javaTypeResolver>
            <property name="forceBigDecimals" value="false"/>
        </javaTypeResolver>
        <!-- 生成模型的包名和位置-->
        <javaModelGenerator targetPackage="com.hy.yyzx.common.model" targetProject="D:/Workspace/yyzx/yyzx-common/src/main/java">
            <property name="enableSubPackages" value="true"/>
            <property name="trimStrings" value="true"/>
        </javaModelGenerator>
        <!-- 生成映射文件的包名和位置-->
        <sqlMapGenerator targetPackage="mapping" targetProject="D:/Workspace/yyzx/yyzx-admin-service/src/main/resources">
            <property name="enableSubPackages" value="true"/>
        </sqlMapGenerator>
         <!--生成DAO的包名和位置-->
        <javaClientGenerator type="XMLMAPPER" targetPackage="com.hy.yyzx.admin.service.mapper" targetProject="D:/Workspace/yyzx/yyzx-admin-service/src/main/java">
            <property name="enableSubPackages" value="true"/>
        </javaClientGenerator>
        <!-- javaServiceGenerator  -->
        <javaServiceGenerator  targetPackage="com.hy.yyzx.admin.service.service"
                               implementationPackage = "com.hy.yyzx.admin.service.service.impl" targetProject="D:/Workspace/yyzx/yyzx-admin-service/src/main/java">
            <property name="enableSubPackages" value="false" />
        </javaServiceGenerator>
       <!-- <table tableName="sys_user" enableCountByExample="true" enableUpdateByExample="true" enableDeleteByExample="true" enableSelectByExample="true" selectByExampleQueryId="true">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>
        <table tableName="sys_config" enableCountByExample="true" enableUpdateByExample="true" enableDeleteByExample="true" enableSelectByExample="true" selectByExampleQueryId="true">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
            <columnOverride column="options" javaType="java.lang.String" jdbcType="VARCHAR" />
            <columnOverride column="remark" javaType="java.lang.String" jdbcType="VARCHAR" />
            <columnOverride column="value" javaType="java.lang.String" jdbcType="VARCHAR" />
        </table>
        <table tableName="sys_log_login" enableCountByExample="true" enableUpdateByExample="true" enableDeleteByExample="true" enableSelectByExample="true" selectByExampleQueryId="true">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>-->
        <table tableName="sys_role_permission" enableCountByExample="true" enableUpdateByExample="true" enableDeleteByExample="true" enableSelectByExample="true" selectByExampleQueryId="true">
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>
    </context>
</generatorConfiguration>